# Generated by Django 4.2.6 on 2023-10-21 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('car_model', models.CharField(choices=[('ek9', 'Honda Civic Type R EK9'), ('ep3', 'Honda Civic Type R EP3'), ('fn2', 'Honda Civic Type R FN2'), ('fd2', 'Honda Civic Type R FD2'), ('fk2', 'Honda Civic Type R FK2'), ('fk8', 'Honda Civic Type R FK8'), ('fl5', 'Honda Civic Type R FL5'), ('dc2', 'Honda Integra Type R DC2'), ('dc5', 'Honda Integra Type R DC5'), ('nsx-r', 'Honda NSX Type R'), ('cl1', 'Honda Accord Type R')], default='ek9', max_length=30)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('county', models.CharField(blank=True, max_length=40, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('postcode', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
