# Generated by Django 4.2.6 on 2023-11-04 19:19

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_name_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='car_model',
            field=models.CharField(choices=[('ek9', 'Honda Civic Type R EK9'), ('ep3', 'Honda Civic Type R EP3'), ('fn2', 'Honda Civic Type R FN2'), ('fd2', 'Honda Civic Type R FD2'), ('fk2', 'Honda Civic Type R FK2'), ('fk8', 'Honda Civic Type R FK8'), ('fl5', 'Honda Civic Type R FL5'), ('dc2', 'Honda Integra Type R DC2'), ('dc5', 'Honda Integra Type R DC5'), ('nsx-r', 'Honda NSX Type R'), ('cl1', 'Honda Accord Type R')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='county',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postcode',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
