# Generated by Django 4.2.6 on 2023-11-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_email',
            field=models.EmailField(blank=True, default='', max_length=70, unique=True),
        ),
    ]
