# Generated by Django 4.2.6 on 2023-11-27 20:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_userprofile_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='defaultProfilePicture', max_length=255, verbose_name='profile-image'),
        ),
    ]
