# Generated by Django 4.2.6 on 2023-11-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_userprofile_facebook_url_userprofile_instagram_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='car_model',
            field=models.CharField(choices=[('select', ''), ('ek9', 'Honda Civic Type R EK9'), ('ep3', 'Honda Civic Type R EP3'), ('fn2', 'Honda Civic Type R FN2'), ('fd2', 'Honda Civic Type R FD2'), ('fk2', 'Honda Civic Type R FK2'), ('fk8', 'Honda Civic Type R FK8'), ('fl5', 'Honda Civic Type R FL5'), ('dc2', 'Honda Integra Type R DC2'), ('dc5', 'Honda Integra Type R DC5'), ('nsx-r', 'Honda NSX Type R'), ('cl1', 'Honda Accord Type R')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_email',
            field=models.EmailField(blank=True, default='', max_length=70),
        ),
    ]
