# Generated by Django 4.2.6 on 2023-12-04 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_userprofile_car_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_email',
            new_name='email_address',
        ),
    ]
