# Generated by Django 4.2.6 on 2023-12-04 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_rename_user_email_userprofile_email_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='facebook_url',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='instagram_url',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='twitter_url',
            new_name='twitter',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='youtube_url',
            new_name='youtube',
        ),
    ]
