# Generated by Django 4.2.6 on 2023-12-27 16:13

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_rename_facebook_url_userprofile_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='car_model',
            field=models.CharField(choices=[('select', 'Select Car model'), ('ek9', 'Honda Civic Type R EK9'), ('ep3', 'Honda Civic Type R EP3'), ('fn2', 'Honda Civic Type R FN2'), ('fd2', 'Honda Civic Type R FD2'), ('fk2', 'Honda Civic Type R FK2'), ('fk8', 'Honda Civic Type R FK8'), ('fl5', 'Honda Civic Type R FL5'), ('dc2', 'Honda Integra Type R DC2'), ('dc5', 'Honda Integra Type R DC5'), ('nsx-r', 'Honda NSX Type R'), ('cl1', 'Honda Accord Type R')], default='Select Car model', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='defaultProfilePicture', max_length=255, verbose_name='image'),
        ),
    ]
