# Generated by Django 4.2.6 on 2023-12-14 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_usercontact_car_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontact',
            old_name='message_content',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='usercontact',
            name='car_model',
        ),
    ]
