# Generated by Django 4.2.6 on 2023-10-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typerforum', '0004_remove_comment_name_comment_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='first_name',
            field=models.CharField(default='someone', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='last_name',
            field=models.CharField(default='someone', max_length=100),
        ),
    ]
