# Generated by Django 4.2.6 on 2023-12-04 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typerforum', '0006_alter_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
