# Generated by Django 4.2.6 on 2023-12-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typerforum', '0007_remove_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='car_model',
            field=models.CharField(choices=[('select', 'Select Car model'), ('ek9', 'Honda Civic Type R EK9'), ('ep3', 'Honda Civic Type R EP3'), ('fn2', 'Honda Civic Type R FN2'), ('fd2', 'Honda Civic Type R FD2'), ('fk2', 'Honda Civic Type R FK2'), ('fk8', 'Honda Civic Type R FK8'), ('fl5', 'Honda Civic Type R FL5'), ('dc2', 'Honda Integra Type R DC2'), ('dc5', 'Honda Integra Type R DC5'), ('nsx-r', 'Honda NSX Type R'), ('cl1', 'Honda Accord Type R')], default='', max_length=30),
        ),
    ]
